baseURL = "https://www.flutterduck.com/"
title = "FlutterDuck - Technology, Buffalo Bills, Pinball, Writing and More"
author = "Fezmid"
theme = "aether"
canonifyurls = true
paginate = 3

[params]
brand = "FlutterDuck"
description = "A place to learn about a little of everything"
bgimg = "img/ignasi_pattern_s.png"
rssinmenu = false

#metaCreator = "Joe Hutchinson"
#metaImage = "img/ogimage.jpg"
