baseURL = "https://www.flutterduck.com/"
title = "Flutter Duck - Technology, Buffalo Bills, Pinball, Writing and More"
author = "Fezmid"
theme = "aether"
canonifyurls = true
paginate = 3

[params]
brand = "FlutterDuck"
description = "A place to learn about a little of everything"
bgimg = "does/not/seem/to/work"
#metaCreator = "Joe Hutchinson"
#metaImage = "img/ogimage.jpg"
