description = "Vendors want you to believe that you need to buy shiny tools to remain secure. The reality is that culture and process matter more."

images = ["Security-Hierarchy.png"]

title = "Security is about culture and process more than tools."
